#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
~/.config/polybar/launch.sh &
nm-applet &
pamac-tray &
compton &
xsetroot -cursor_name left_ptr &
setxkbmap -option caps:swapescape &
sleep 1 && /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           0
bspc config top_padding          20
bspc config bottom_padding       0
bspc config focused_border_color #84A0C6
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

