#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
compton &
nitrogen --restore &
~/.config/polybar/launch.sh &
nm-applet &
pamac-tray &
sleep 1 && /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
flameshot &
xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


